/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  youtubeUrl: string;
  videoType: "charla" | "taller" | "otro";
  topics: Array<
    {
      _key: string;
    } & TopicReference
  >;
  publishedAt: string;
  featured?: boolean;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Material = {
  _id: string;
  _type: "material";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  cover?: AccessibleImage;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
  source?: string;
  topics: Array<
    {
      _key: string;
    } & TopicReference
  >;
  publishedAt: string;
  featured?: boolean;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  mainImage: AccessibleImage;
  content: BlockContent;
  topics: Array<
    {
      _key: string;
    } & TopicReference
  >;
  publishedAt: string;
  reviewedAt?: string;
  author?: string;
  featured?: boolean;
  seo?: Seo;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TopicReference
  | Video
  | Seo
  | Slug
  | SanityFileAssetReference
  | Material
  | SanityImageAssetReference
  | AccessibleImage
  | Article
  | BlockContent
  | Topic
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/articles.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[    _type == "article" &&    !(_id in path("drafts.**")) &&    slug.current == $slug  ][0] {    _id,    _type,    title,    "slug": slug.current,    summary,    mainImage,    content,    "topics": topics[]->{      _id,      name,      "slug": slug.current    },    publishedAt,    reviewedAt,    author,    featured,    seo  }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "article";
  title: string;
  slug: string;
  summary: string;
  mainImage: AccessibleImage;
  content: BlockContent;
  topics: Array<{
    _id: string;
    name: string;
    slug: string;
  }>;
  publishedAt: string;
  reviewedAt: string | null;
  author: string | null;
  featured: boolean | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries/articles.ts
// Variable: RELATED_RESOURCES_QUERY
// Query: *[    _type in ["article", "material", "video"] &&    !(_id in path("drafts.**")) &&    _id != $articleId &&    count(topics[_ref in $topicIds]) > 0  ]    | order(featured desc, publishedAt desc, _id asc)[0...3] {      _id,      _type,      title,      "slug": slug.current,      publishedAt,      featured,      "topics": topics[]->{        _id,        name,        "slug": slug.current      },      _type == "article" => {        summary,        mainImage      },      _type == "material" => {        description,        cover,        source      },      _type == "video" => {        description,        videoType,        youtubeUrl      }    }
export type RELATED_RESOURCES_QUERY_RESULT = Array<
  | {
      _id: string;
      _type: "article";
      title: string;
      slug: string;
      publishedAt: string;
      featured: boolean | null;
      topics: Array<{
        _id: string;
        name: string;
        slug: string;
      }>;
      summary: string;
      mainImage: AccessibleImage;
    }
  | {
      _id: string;
      _type: "material";
      title: string;
      slug: string;
      publishedAt: string;
      featured: boolean | null;
      topics: Array<{
        _id: string;
        name: string;
        slug: string;
      }>;
      description: string;
      cover: AccessibleImage | null;
      source: string | null;
    }
  | {
      _id: string;
      _type: "video";
      title: string;
      slug: string;
      publishedAt: string;
      featured: boolean | null;
      topics: Array<{
        _id: string;
        name: string;
        slug: string;
      }>;
      description: string;
      videoType: "charla" | "otro" | "taller";
      youtubeUrl: string;
    }
>;

// Source: src/sanity/queries/resources.ts
// Variable: RESOURCES_QUERY
// Query: {    "items": *[      _type in ["article", "material", "video"] &&      !(_id in path("drafts.**")) &&      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&      (!defined($resourceType) || _type == $resourceType)    ]      | order(featured desc, publishedAt desc, _id asc)[$start...$end] {        _id,        _type,        title,        "slug": slug.current,        publishedAt,        featured,        "topics": topics[]->{          _id,          name,          "slug": slug.current        },        _type == "article" => {          summary,          mainImage        },        _type == "material" => {          description,          cover,          source        },        _type == "video" => {          description,          videoType,          youtubeUrl        }      },    "total": count(*[      _type in ["article", "material", "video"] &&      !(_id in path("drafts.**")) &&      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&      (!defined($resourceType) || _type == $resourceType)    ])  }
export type RESOURCES_QUERY_RESULT = {
  items: Array<
    | {
        _id: string;
        _type: "article";
        title: string;
        slug: string;
        publishedAt: string;
        featured: boolean | null;
        topics: Array<{
          _id: string;
          name: string;
          slug: string;
        }>;
        summary: string;
        mainImage: AccessibleImage;
      }
    | {
        _id: string;
        _type: "material";
        title: string;
        slug: string;
        publishedAt: string;
        featured: boolean | null;
        topics: Array<{
          _id: string;
          name: string;
          slug: string;
        }>;
        description: string;
        cover: AccessibleImage | null;
        source: string | null;
      }
    | {
        _id: string;
        _type: "video";
        title: string;
        slug: string;
        publishedAt: string;
        featured: boolean | null;
        topics: Array<{
          _id: string;
          name: string;
          slug: string;
        }>;
        description: string;
        videoType: "charla" | "otro" | "taller";
        youtubeUrl: string;
      }
  >;
  total: number;
};

// Source: src/sanity/queries/resources.ts
// Variable: RESOURCES_OLDEST_QUERY
// Query: {    "items": *[      _type in ["article", "material", "video"] &&      !(_id in path("drafts.**")) &&      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&      (!defined($resourceType) || _type == $resourceType)    ]      | order(featured desc, publishedAt asc, _id asc)[$start...$end] {        _id,        _type,        title,        "slug": slug.current,        publishedAt,        featured,        "topics": topics[]->{          _id,          name,          "slug": slug.current        },        _type == "article" => {          summary,          mainImage        },        _type == "material" => {          description,          cover,          source        },        _type == "video" => {          description,          videoType,          youtubeUrl        }      },    "total": count(*[      _type in ["article", "material", "video"] &&      !(_id in path("drafts.**")) &&      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&      (!defined($resourceType) || _type == $resourceType)    ])  }
export type RESOURCES_OLDEST_QUERY_RESULT = {
  items: Array<
    | {
        _id: string;
        _type: "article";
        title: string;
        slug: string;
        publishedAt: string;
        featured: boolean | null;
        topics: Array<{
          _id: string;
          name: string;
          slug: string;
        }>;
        summary: string;
        mainImage: AccessibleImage;
      }
    | {
        _id: string;
        _type: "material";
        title: string;
        slug: string;
        publishedAt: string;
        featured: boolean | null;
        topics: Array<{
          _id: string;
          name: string;
          slug: string;
        }>;
        description: string;
        cover: AccessibleImage | null;
        source: string | null;
      }
    | {
        _id: string;
        _type: "video";
        title: string;
        slug: string;
        publishedAt: string;
        featured: boolean | null;
        topics: Array<{
          _id: string;
          name: string;
          slug: string;
        }>;
        description: string;
        videoType: "charla" | "otro" | "taller";
        youtubeUrl: string;
      }
  >;
  total: number;
};

// Source: src/sanity/queries/topics.ts
// Variable: TOPICS_QUERY
// Query: *[    _type == "topic" &&    !(_id in path("drafts.**"))  ] | order(order asc, name asc) {    _id,    name,    "slug": slug.current,    description,    order  }
export type TOPICS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  order: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "article" &&\n    !(_id in path("drafts.**")) &&\n    slug.current == $slug\n  ][0] {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    summary,\n    mainImage,\n    content,\n    "topics": topics[]->{\n      _id,\n      name,\n      "slug": slug.current\n    },\n    publishedAt,\n    reviewedAt,\n    author,\n    featured,\n    seo\n  }\n': ARTICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[\n    _type in ["article", "material", "video"] &&\n    !(_id in path("drafts.**")) &&\n    _id != $articleId &&\n    count(topics[_ref in $topicIds]) > 0\n  ]\n    | order(featured desc, publishedAt desc, _id asc)[0...3] {\n      _id,\n      _type,\n      title,\n      "slug": slug.current,\n      publishedAt,\n      featured,\n      "topics": topics[]->{\n        _id,\n        name,\n        "slug": slug.current\n      },\n      _type == "article" => {\n        summary,\n        mainImage\n      },\n      _type == "material" => {\n        description,\n        cover,\n        source\n      },\n      _type == "video" => {\n        description,\n        videoType,\n        youtubeUrl\n      }\n    }\n': RELATED_RESOURCES_QUERY_RESULT;
    '\n  {\n    "items": *[\n      _type in ["article", "material", "video"] &&\n      !(_id in path("drafts.**")) &&\n      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&\n      (!defined($resourceType) || _type == $resourceType)\n    ]\n      | order(featured desc, publishedAt desc, _id asc)[$start...$end] {\n        _id,\n        _type,\n        title,\n        "slug": slug.current,\n        publishedAt,\n        featured,\n        "topics": topics[]->{\n          _id,\n          name,\n          "slug": slug.current\n        },\n        _type == "article" => {\n          summary,\n          mainImage\n        },\n        _type == "material" => {\n          description,\n          cover,\n          source\n        },\n        _type == "video" => {\n          description,\n          videoType,\n          youtubeUrl\n        }\n      },\n    "total": count(*[\n      _type in ["article", "material", "video"] &&\n      !(_id in path("drafts.**")) &&\n      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&\n      (!defined($resourceType) || _type == $resourceType)\n    ])\n  }\n': RESOURCES_QUERY_RESULT;
    '\n  {\n    "items": *[\n      _type in ["article", "material", "video"] &&\n      !(_id in path("drafts.**")) &&\n      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&\n      (!defined($resourceType) || _type == $resourceType)\n    ]\n      | order(featured desc, publishedAt asc, _id asc)[$start...$end] {\n        _id,\n        _type,\n        title,\n        "slug": slug.current,\n        publishedAt,\n        featured,\n        "topics": topics[]->{\n          _id,\n          name,\n          "slug": slug.current\n        },\n        _type == "article" => {\n          summary,\n          mainImage\n        },\n        _type == "material" => {\n          description,\n          cover,\n          source\n        },\n        _type == "video" => {\n          description,\n          videoType,\n          youtubeUrl\n        }\n      },\n    "total": count(*[\n      _type in ["article", "material", "video"] &&\n      !(_id in path("drafts.**")) &&\n      (!defined($topicSlug) || $topicSlug in topics[]->slug.current) &&\n      (!defined($resourceType) || _type == $resourceType)\n    ])\n  }\n': RESOURCES_OLDEST_QUERY_RESULT;
    '\n  *[\n    _type == "topic" &&\n    !(_id in path("drafts.**"))\n  ] | order(order asc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    order\n  }\n': TOPICS_QUERY_RESULT;
  }
}
