export { BookIcon } from "./BookIcon";
export type { BookIconProps } from "./BookIcon";
export { CommunityIcon } from "./CommunityIcon";
export type { CommunityIconProps } from "./CommunityIcon";
export { EarIcon } from "./EarIcon";
export type { EarIconProps } from "./EarIcon";
export { FacebookIcon } from "./FacebookIcon";
export type { FacebookIconProps } from "./FacebookIcon";
export { HeartIcon } from "./HeartIcon";
export type { HeartIconProps } from "./HeartIcon";
export { HomeIcon } from "./HomeIcon";
export type { HomeIconProps } from "./HomeIcon";
export type { IconProps } from "./icon.types";
export { LocationIcon } from "./LocationIcon";
export type { LocationIconProps } from "./LocationIcon";
export { MailIcon } from "./MailIcon";
export type { MailIconProps } from "./MailIcon";
export { MenuIcon } from "./MenuIcon";
export type { MenuIconProps } from "./MenuIcon";
export { PeopleIcon } from "./PeopleIcon";
export type { PeopleIconProps } from "./PeopleIcon";
export { PhoneIcon } from "./PhoneIcon";
export type { PhoneIconProps } from "./PhoneIcon";
export { WhatsAppIcon } from "./WhatsAppIcon";
export type { WhatsAppIconProps } from "./WhatsAppIcon";
